### ISSUE TITLE
Pre-built Docker image

### ISSUE THREAD

**Issue by nwithan8** [freetonik/textpod#11]
Please consider releasing a pre-built Docker image on Docker Hub or GitHub Container Registry

**Comment by freetonik** [comment]
Will do, thanks for the suggestion 👍

**Comment by mariushosting** [comment]
Is the image textpod-docker:latest already released?

**Comment by freetonik** [comment]
Yes, it's available at https://hub.docker.com/r/freetonik/textpod as `freetonik/textpod:latest`. Get it with `docker pull freetonik/textpod`.

**Comment by nwithan8** [comment]
Thanks! I used the new image to build a template for the Unraid Community Apps Store so Unraid users can easily set up this Docker container on their servers.

**Comment by freetonik** [comment]
Very cool! Thanks!
