### ISSUE TITLE
Button to save notes

### ISSUE THREAD

**Issue by meldarionqeusse** [freetonik/textpod#19]
On mobile it is not possible to use CTRL + ENTER so saving from a mobile device seems to be impossible at the moment.

**Comment by freetonik** [comment]
Good point, will do. I'll start planning milestone releases and plan features per release.

**Comment by freetonik** [comment]
Hey! A submit button is now implemented thanks to @cliffeh , available in the newest version 0.1.3 
 https://github.com/freetonik/textpod/releases/tag/0.1.3
