### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by khannover** [freetonik/textpod#2]
Hey,

i really like your app. But i needed support for Docker, so i created a fork (which is actually a wrapper for installing textpod) [here](https://github.com/khannover/textpod-docker). 

Just wanted to let you know, but maybe you could integrate support for Docker in your repo?

**Comment by freetonik** [comment]
Hey!
Thanks! I think I'll keep the repo as minimal as possible for now, hopefully your Docker fork will not need to be updated too often, I'll try to keep the CLI interface backwards compatible.
