### ISSUE TITLE
Ability to add TODO List

### ISSUE THREAD

**Issue by prassee** [freetonik/textpod#21]
Started to use this to save URL's, would be more useful if we have a TODO list

**Comment by freetonik** [comment]
Hey!

You can create checkboxes by using github-flavoured markdown like so:

```
- [ ] todo
```

The actual checking/unchecking is planned, but probably not for the next release.

**Comment by freetonik** [comment]
The actual implementation of checklists is now tracked here https://github.com/freetonik/textpod/issues/6
