### ISSUE TITLE
homebrew support

### ISSUE THREAD

**Issue by e-minguez** [freetonik/textpod#5]
First of all, thank you for this. I think this is what I needed for me to take notes and keep a "journal".

It would be nice for osx users to make it available via homebrew :)

Thanks!

**Comment by freetonik** [comment]
Hey! Thanks!
Yeah, I was planning to, just didn't have time yet.

**Comment by freetonik** [comment]
Hey!

Now it's available via homebrew:

```
brew tap freetonik/tap
brew install textpod
```
